### ISSUE TITLE
error 500

### ISSUE THREAD

**Issue by chomatz** [pbruna/zimbra_preauth_router#1]
followed the steps using docker but got the following error

App 143 stdout: 
App 143 stdout: ------------------------------------------------
App 143 stdout: Starting server with the following configuration
App 143 stdout: Domain: test.net
App 143 stdout: Logo img: http://blog.itlinux.cl/images/ZBox.png
App 143 stdout: Users File: /opt/zimbra_preauth_router/users.yml
App 143 stdout: Old BackendURL: http://192.168.2.249
App 143 stdout: New BackendURL: http://192.168.2.242
App 143 stdout: Old Preauth Key: f81bf7f32855339f71fe4cb86ddbd981654aeb49fd03c31e19524f8dfc6ff1bc
App 143 stdout: New Preauth Key: f81bf7f32855339f71fe4cb86ddbd981654aeb49fd03c31e19524f8dfc6ff1bc
App 143 stdout: ------------------------------------------------
[ 2015-07-06 09:42:47.5958 124/7fb902c06700 Pool2/SmartSpawner.h:298 ]: Preloader for /home/app/zimbra_pre_auth_router started on PID 143, listening on unix:/tmp/passenger.1.0.111/generation-0/backends/preloader.lpe9jz
App 159 stdout: 
**App 143 stderr: 2015-07-06 09:42:47 - NoMethodError - private method `select' called for nil:NilClass:**
App 143 stderr:     /home/app/zimbra_pre_auth_router/lib/zimbra_pre_auth_router/login.rb:25:in `authenticate!'
App 143 stderr:     /home/app/zimbra_pre_auth_router/lib/zimbra_pre_auth_router/login.rb:16:in `set_token'
App 143 stderr:     /home/app/zimbra_pre_auth_router/lib/zimbra_pre_auth_router/login.rb:8:in `initialize'
App 143 stderr:     /home/app/zimbra_pre_auth_router/lib/zimbra_pre_auth_router/user.rb:62:in `new'
App 143 stderr:     /home/app/zimbra_pre_auth_router/lib/zimbra_pre_auth_router/user.rb:62:in `login'
App 143 stderr:     /home/app/zimbra_pre_auth_router/app.rb:21:in `block in class:App'
App 143 stderr:     /var/lib/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1610:in `call'
App 143 stderr:     /var/lib/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1610:in `block in compile!'
App 143 stderr:     /var/lib/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in `[]'
App 143 stderr:     /var/lib/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in `block (3 levels) in route!'
App 143 stderr:     /var/lib/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:993:in `route_eval'
App 143 stderr:     /var/lib/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in `block (2 levels) in route!'
App 143 stderr:     /var/lib/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1014:in `block in process_route'
App 143 stderr:     /var/lib/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1012:in `catch'
App 143 stderr:     /var/lib/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1012:in `process_route'
App 143 stderr:     /var/lib/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:972:in `block in route!'
App 143 stderr:     /var/lib/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:971:in `each'
App 143 stderr:     /var/lib/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:971:in `route!'
App 143 stderr:     /var/lib/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1084:in `block in dispatch!'
App 143 stderr:     /var/lib/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `block in invoke'
App 143 stderr:     /var/lib/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `catch'
App 143 stderr:     /var/lib/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `invoke'
App 143 stderr:     /var/lib/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1081:in `dispatch!'
App 143 stderr:     /var/lib/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:906:in `block in call!'
App 143 stderr:     /var/lib/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `block in invoke'
App 143 stderr:     /var/lib/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `catch'
App 143 stderr:     /var/lib/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `invoke'
App 143 stderr:     /var/lib/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:906:in `call!'
App 143 stderr:     /var/lib/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:894:in `call'
App 143 stderr:     /var/lib/gems/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
App 143 stderr:     /var/lib/gems/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
App 143 stderr:     /var/lib/gems/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
App 143 stderr:     /var/lib/gems/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
App 143 stderr:     /var/lib/gems/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
App 143 stderr:     /var/lib/gems/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
App 143 stderr:     /var/lib/gems/2.1.0/gems/rack-1.6.0/lib/rack/logger.rb:15:in `call'
App 143 stderr:     /var/lib/gems/2.1.0/gems/rack-1.6.0/lib/rack/commonlogger.rb:33:in `call'
App 143 stderr:     /var/lib/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:218:in `call'
App 143 stderr:     /var/lib/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:211:in `call'
App 143 stderr:     /var/lib/gems/2.1.0/gems/rack-1.6.0/lib/rack/head.rb:13:in `call'
App 143 stderr:     /var/lib/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:181:in `call'
App 143 stderr:     /var/lib/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:2021:in `call'
App 143 stderr:     /var/lib/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1486:in `block in call'
App 143 stderr:     /var/lib/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1795:in `synchronize'
App 143 stderr:     /var/lib/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1486:in `call'
App 143 stderr:     /usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:74:in `process_request'
App 143 stderr:     /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:141:in `accept_and_process_next_request'
App 143 stderr:     /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:109:in `main_loop'
App 143 stderr:     /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:455:in `block (3 levels) in start_threads'
App 143 stderr: 192.168.2.228 - - [06/Jul/2015:09:42:47 +0000] "POST /login " 500 30 0.0464

**Comment by pbruna** [comment]
Hi @chomatz 
I think it was a problem with the authentication path parameter. Now is fixed, could you please give it a try and let me know how it goes?

**Comment by chomatz** [comment]
hi

i went and rebuilt my test setup but i still can't seem to get it to work...

here's the settings on the first server (z1.test.net)

[zimbra@z1 ~]$ zmprov gd test.net zimbraPreAuthKey

# name test.net

zimbraPreAuthKey: 0112f91f1c35c3c10af285781ea420bce60d03d2edb5e852199c599e20177558
[zimbra@z1 ~]$ zmprov ga z1.admin@test.net zimbraId

# name z1.admin@test.net

zimbraId: 647c71cf-41cc-4433-8a7c-e7a834f3f101
[zimbra@z1 ~]$ zmcontrol -v
Release 8.6.0_GA_1153.RHEL7_64_20141215151204 RHEL7_64 NETWORK edition.

here's the settings on the second server (z2.test.net)

[zimbra@z2 ~]$ zmprov gd test.net zimbraPreAuthKey

# name test.net

zimbraPreAuthKey: 71fc3aa69122e18ca578c80f2bf90e51e36fcad35a5b6060cb5007ed649b3cbc
[zimbra@z2 ~]$ zmprov ga z2.admin@test.net zimbraId

# name z2.admin@test.net

zimbraId: cc0c177a-ef5a-4c2d-b47f-7f34075cccaa
[zimbra@z2 ~]$ zmcontrol -v
Release 8.6.0_GA_1153.RHEL7_64_20141215151204 RHEL7_64 NETWORK edition.

here's my users.yml file

[root@zr ~]# cat /opt/zpr/users.yml 
z1.admin@test.net: "647c71cf-41cc-4433-8a7c-e7a834f3f101"
z2.admin@test.net: "cc0c177a-ef5a-4c2d-b47f-7f34075cccaa"

and finally here's how i run docker

docker run -p 80:80 -v /opt/zpr:/opt/zpr \
-e "DOMAIN=test.net" \
-e "OLD_BACKEND=http://z1.test.net" \
-e "NEW_BACKEND=http://z2.test.net" \
-e "OLD_PREAUTH_KEY=0112f91f1c35c3c10af285781ea420bce60d03d2edb5e852199c599e20177558" \
-e "NEW_PREAUTH_KEY=71fc3aa69122e18ca578c80f2bf90e51e36fcad35a5b6060cb5007ed649b3cbc" \
-e "LOGO=http://blog.itlinux.cl/images/ZBox.png" \
-e "USERS_FILE=/opt/zpr/users.yml" \
pbruna/zimbra_preauth_router

here's the output that i get

App 137 stdout: 
App 137 stdout: ------------------------------------------------
App 137 stdout: Starting server with the following configuration
App 137 stdout: Domain: test.net
App 137 stdout: Logo img: http://blog.itlinux.cl/images/ZBox.png
App 137 stdout: Users File: /opt/zpr/users.yml
App 137 stdout: Old BackendURL: http://z1.test.net
App 137 stdout: New BackendURL: http://z2.test.net
App 137 stdout: Old Preauth Key: 0112f91f1c35c3c10af285781ea420bce60d03d2edb5e852199c599e20177558
App 137 stdout: New Preauth Key: 71fc3aa69122e18ca578c80f2bf90e51e36fcad35a5b6060cb5007ed649b3cbc
App 137 stdout: ------------------------------------------------
[ 2015-09-03 09:41:37.4381 118/7f655ad96700 Pool2/SmartSpawner.h:298 ]: Preloader for /home/app/zimbra_pre_auth_router started on PID 137, listening on unix:/tmp/passenger.1.0.105/generation-0/backends/preloader.17jtfss
App 153 stdout: 
App 137 stderr: 192.168.2.231 - - [03/Sep/2015:09:41:37 +0000] "GET / " 200 2033 0.0318
App 137 stderr: 2015-09-03 09:41:53 - NoMethodError - private method `select' called for nil:NilClass:
App 137 stderr:     /home/app/zimbra_pre_auth_router/lib/zimbra_pre_auth_router/login.rb:25:in`authenticate!'
App 137 stderr:     /home/app/zimbra_pre_auth_router/lib/zimbra_pre_auth_router/login.rb:16:in `set_token'
App 137 stderr:     /home/app/zimbra_pre_auth_router/lib/zimbra_pre_auth_router/login.rb:8:in`initialize'
App 137 stderr:     /home/app/zimbra_pre_auth_router/lib/zimbra_pre_auth_router/user.rb:62:in `new'
App 137 stderr:     /home/app/zimbra_pre_auth_router/lib/zimbra_pre_auth_router/user.rb:62:in`login'
App 137 stderr:     /home/app/zimbra_pre_auth_router/app.rb:21:in `block in <class:App>'
App 137 stderr:     /var/lib/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1610:in`call'
App 137 stderr:     /var/lib/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1610:in `block in compile!'
App 137 stderr:     /var/lib/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in`[]'
App 137 stderr:     /var/lib/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in `block (3 levels) in route!'
App 137 stderr:     /var/lib/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:993:in`route_eval'
App 137 stderr:     /var/lib/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in `block (2 levels) in route!'
App 137 stderr:     /var/lib/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1014:in`block in process_route'
App 137 stderr:     /var/lib/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1012:in `catch'
App 137 stderr:     /var/lib/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1012:in`process_route'
App 137 stderr:     /var/lib/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:972:in `block in route!'
App 137 stderr:     /var/lib/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:971:in`each'
App 137 stderr:     /var/lib/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:971:in `route!'
App 137 stderr:     /var/lib/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1084:in`block in dispatch!'
App 137 stderr:     /var/lib/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `block in invoke'
App 137 stderr:     /var/lib/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in`catch'
App 137 stderr:     /var/lib/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `invoke'
App 137 stderr:     /var/lib/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1081:in`dispatch!'
App 137 stderr:     /var/lib/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:906:in `block in call!'
App 137 stderr:     /var/lib/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in`block in invoke'
App 137 stderr:     /var/lib/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `catch'
App 137 stderr:     /var/lib/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in`invoke'
App 137 stderr:     /var/lib/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:906:in `call!'
App 137 stderr:     /var/lib/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:894:in`call'
App 137 stderr:     /var/lib/gems/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
App 137 stderr:     /var/lib/gems/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in`call'
App 137 stderr:     /var/lib/gems/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
App 137 stderr:     /var/lib/gems/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in`call'
App 137 stderr:     /var/lib/gems/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
App 137 stderr:     /var/lib/gems/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in`call'
App 137 stderr:     /var/lib/gems/2.1.0/gems/rack-1.6.0/lib/rack/logger.rb:15:in `call'
App 137 stderr:     /var/lib/gems/2.1.0/gems/rack-1.6.0/lib/rack/commonlogger.rb:33:in`call'
App 137 stderr:     /var/lib/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:218:in `call'
App 137 stderr:     /var/lib/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:211:in`call'
App 137 stderr:     /var/lib/gems/2.1.0/gems/rack-1.6.0/lib/rack/head.rb:13:in `call'
App 137 stderr:     /var/lib/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:181:in`call'
App 137 stderr:     /var/lib/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:2021:in `call'
App 137 stderr:     /var/lib/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1486:in`block in call'
App 137 stderr:     /var/lib/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1795:in `synchronize'
App 137 stderr:     /var/lib/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1486:in`call'
App 137 stderr:     /usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:74:in `process_request'
App 137 stderr:     /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:141:in`accept_and_process_next_request'
App 137 stderr:     /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:109:in `main_loop'
App 137 stderr:     /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:455:in`block (3 levels) in start_threads'
App 137 stderr: 
App 137 stderr: 192.168.2.231 - - [03/Sep/2015:09:41:53 +0000] "POST /login " 500 30 6.4630

**Comment by pbruna** [comment]
Im really sorry about this, please give me until the end of the day to return to the office and fix it once and for all.

Question: are you using Zimbra Proxy or just the Zimbra Mailbox?

**Comment by chomatz** [comment]
thank you for taking the time to look into this issue... i have tried
setups with and without the proxies but i get the same problem... this
setup is just using the mailboxes...
